In [1]:
import requests

# x = requests.get('https://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=aa863bfc074f43ddbb2154333210112&q=nasik&format=csv&date=2015-05-25&enddate=2021-12-01&tp=1')

# print(x.text)

In [ ]:
# txt = x.text
# print(txt)

In [ ]:
# f = open('csvfile.csv','w')
# f.write(txt) #Give your csv text here.
# ## Python will convert \n to os.linesep
# f.close()

In [ ]:
# !dir

In [2]:
import pandas as pd

# df = pd.read_csv(r'csvfile.csv', skiprows=5, header=None)  # sep=",", error_bad_lines=False
# df.head()

In [ ]:
# import pprint
# file1 = open("csvfile.csv","r")
# pprint.pprint(file1.read())

In [ ]:
# df[0][3].replace('-','')

In [ ]:
# df[0][875] # .replace('-','')

In [ ]:
# df.to_csv(df[0][3].replace('-','')+'.csv', index=False)

In [1]:
import os
import glob
import random
import requests
import numpy as np
import pandas as pd

In [ ]:
_date = '2018-01-01'
index = 0

for ind in range(36):
    x = requests.get(f'https://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=aa863bfc074f43ddbb2154333210112&q=nasik&format=csv&date={_date}&enddate=2021-12-01&tp=1')
    txt = x.text
    f = open('csvfile.csv','w')
    f.write(txt) 
    f.close()
    df = pd.read_csv(r'csvfile.csv', skiprows=5, header=None)  # sep=",", error_bad_lines=False
    filename = df[0][3].replace('-','')
#     _date = df[0][875]
    _date = df[0][len(df)-1]
    df.to_csv('part1\\'+str(index)+'_'+filename+'.csv', index=False)
    index += 1
    df = 0
    os.remove("csvfile.csv")

In [ ]:
# df

In [ ]:
# filename = df[0][3].replace('-','')
# # _date = df[0][875]
# df.to_csv(filename+'.csv', index=False)
# df = 0
# os.remove("csvfile.csv")

In [ ]:
# !dir

In [4]:
file_list = glob.glob('part1\\*.csv')
print(file_list[2])

part1\11_20190110.csv

In [5]:
file_list[2].split('\\')[1].split('_')[0]

'11'

In [6]:
df = pd.read_csv(file_list[0])
df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,#date,time,tempC,tempF,windspeedMiles,windspeedKmph,winddirdegree,winddir16point,weatherCode,weatherIconUrl,...,HeatIndexC,HeatIndexF,DewPointC,DewPointF,WindChillC,WindChillF,WindGustMiles,WindGustKmph,FeelsLikeC,FeelsLikeF
1,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,27,81,17,63,07:10 AM,06:07 PM,05:31 PM,06:00 AM,Waxing Gibbous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01,0,19,66,3,4,53,NE,113,http://cdn.worldweatheronline.com/images/wsymb...,...,19,66,7,45,19,66,6,9,19,66

In [7]:
cols_name = list(df.iloc[0])

In [8]:
drop_row = [0,1,2]


for ind in range(len(df)):
    if df['1'][ind] == '0':
#         print(ind-1, df['1'][ind-1])
        drop_row.append(ind-1)
        
update_df = df.drop(drop_row)
 
update_df = update_df.reset_index(drop=True)

update_df.columns = cols_name

In [ ]:
update_df.to_csv('data//0.csv', index=False)

In [ ]:

for file_list in range(len(glob.glob('part1//*.csv'))):
    for all_path in glob.glob('part1//*.csv'):
        if str(file_list) == all_path.split('\\')[1].split('_')[0]:
#             print(file_list, all_path.split('\\')[1].split('_')[0], all_path)
        
            df = pd.read_csv(all_path)
            cols_name = list(df.iloc[0])
            drop_row = [0,1,2]

            for ind in range(len(df)):
                if df['1'][ind] == '0':
                    drop_row.append(ind-1)

            update_df = df.drop(drop_row)

            update_df = update_df.reset_index(drop=True)

            update_df.columns = cols_name

            update_df.to_csv('part2//'+str(file_list)+'.csv', index=False)

In [ ]:
df0 = pd.DataFrame(columns=cols_name)


for file_list in range(len(glob.glob('part2//*.csv'))):
    for all_path in glob.glob('part2//*.csv'):
#         print(file_list, all_path.split('\\')[1].split('.')[0])
        if str(file_list) == all_path.split('\\')[1].split('.')[0]:
            print(file_list, all_path.split('\\')[1].split('.')[0], all_path)

            dfn = pd.read_csv(all_path)
        #     display(dfn.head(2))
            df0 = pd.concat([df0, dfn], axis=0)
#             display(df0.tail(3))
#             df0.reset_index(drop=True)
df0.reset_index(drop=True)
df0.shape

In [ ]:
# df0.head(3)
# df0.tail(3)
df0.shape

In [ ]:
# df0.iloc[26260:]
df0.reset_index(drop=True)

In [ ]:
print(len(df0))
# dropping duplicate values
df0.drop_duplicates(subset = cols_name, keep = False, inplace = True)
print(len(df0))

In [ ]:
df0.to_csv('part3//2019-2021.csv', index=False)

In [ ]:
df0.head(2)

In [ ]:
df0.shape

In [ ]:
df0.info()

In [ ]:
# df0["time"] = pd.to_numeric(df0["time"])
df0['time'] = df0['time'].astype(int)
df0["tempC"] = pd.to_numeric(df0["tempC"])
df0["windspeedKmph"] = pd.to_numeric(df0["windspeedKmph"])
df0[['precipMM']] = df0[['precipMM']].astype(float)
df0["humidity"] = pd.to_numeric(df0["humidity"])
df0["pressureMB"] = pd.to_numeric(df0["pressureMB"])

In [ ]:
# df.describe()

In [ ]:
observation, tempC_7to8, tempC_1to2, tempC_6to7, humidity_7to8, humidity_1to2, humidity_6to7 = [],[],[],[],[],[],[]

for ind in range(0, len(df0)):
#     print(df0['time'][ind])
#     print(ind,'time : ',type(df0['time'][ind]))
    try:
        if str(df0['time'][ind]) == '700':
            print('At 7 to 8 : ', df0['#date'][ind], df0['tempC'][ind], df0['humidity'][ind], df0['windspeedKmph'][ind])
    except:
        print(ind, df0['time'][ind])

In [ ]:
df = pd.read_csv(r'part3//2018-2021.csv')
df.head(3)

In [ ]:
observation = [] 
tempC_7to8, tempC_1to2, tempC_6to7 = [],[],[] 
humidity_7to8, humidity_1to2, humidity_6to7 = [],[],[]
windspeedKmph_7to8, windspeedKmph_1to2, windspeedKmph_6to7 = [],[],[]
pressureMB_7to8, pressureMB_1to2, pressureMB_6to7 = [],[],[]
precipMM_7to8, precipMM_1to2, precipMM_6to7 = [],[],[]
weatherDesc_7to8, weatherDesc_1to2, weatherDesc_6to7 = [],[],[]

for ind in range(len(df)):
    if df['time'][ind] == 700:
#         print(df['time'][ind])
        print('At 7 to 8 : ', df['#date'][ind], df['tempC'][ind], df['humidity'][ind], df['windspeedKmph'][ind],
             df['pressureMB'][ind], df['precipMM'][ind], df['weatherDesc'][ind])
        
        observation.append(df['#date'][ind])
        tempC_7to8.append(df['tempC'][ind])
        humidity_7to8.append(df['humidity'][ind])
        windspeedKmph_7to8.append(df['windspeedKmph'][ind])
        pressureMB_7to8.append(df['pressureMB'][ind])
        precipMM_7to8.append(df['precipMM'][ind])
        weatherDesc_7to8.append(df['weatherDesc'][ind])
        
        
    if df['time'][ind] == 1300:
#         print(df['time'][ind])
        print('At 1 to 2 : ', df['#date'][ind], df['tempC'][ind], df['humidity'][ind], df['windspeedKmph'][ind],
             df['pressureMB'][ind], df['precipMM'][ind], df['weatherDesc'][ind])
        
        tempC_1to2.append(df['tempC'][ind])
        humidity_1to2.append(df['humidity'][ind])
        windspeedKmph_1to2.append(df['windspeedKmph'][ind])
        pressureMB_1to2.append(df['pressureMB'][ind])
        precipMM_1to2.append(df['precipMM'][ind])
        weatherDesc_1to2.append(df['weatherDesc'][ind])
        
        
    if df['time'][ind] == 1800:
#         print(df['time'][ind])
        print('At 6 to 7 : ', df['#date'][ind], df['tempC'][ind], df['humidity'][ind], df['windspeedKmph'][ind],
             df['pressureMB'][ind], df['precipMM'][ind], df['weatherDesc'][ind])
        
        tempC_6to7.append(df['tempC'][ind])
        humidity_6to7.append(df['humidity'][ind])
        windspeedKmph_6to7.append(df['windspeedKmph'][ind])
        pressureMB_6to7.append(df['pressureMB'][ind])
        precipMM_6to7.append(df['precipMM'][ind])
        weatherDesc_6to7.append(df['weatherDesc'][ind])

In [ ]:
print(len(observation))
print(len(tempC_7to8))
print(len(humidity_7to8))
print(len(windspeedKmph_7to8))
print(len(pressureMB_7to8))
print(len(precipMM_7to8))
print(len(weatherDesc_7to8))

In [ ]:
print(len(observation))
print(len(tempC_1to2))
print(len(humidity_1to2))
print(len(windspeedKmph_1to2))
print(len(pressureMB_1to2))
print(len(precipMM_1to2))
print(len(weatherDesc_1to2))

In [ ]:
print(len(observation))
print(len(tempC_6to7))
print(len(humidity_6to7))
print(len(windspeedKmph_6to7))
print(len(pressureMB_6to7))
print(len(precipMM_6to7))
print(len(weatherDesc_6to7))

In [ ]:
df_main = pd.DataFrame()

df_main['observation'] = observation

df_main['tempC_7to8'] = tempC_7to8
df_main['tempC_1to2'] = tempC_1to2
df_main['tempC_6to7'] = tempC_6to7

df_main['humidity_7to8'] = humidity_7to8
df_main['humidity_1to2'] = humidity_1to2
df_main['humidity_6to7'] = humidity_6to7

df_main['windspeedKmph_7to8'] = windspeedKmph_7to8
df_main['windspeedKmph_1to2'] = windspeedKmph_1to2
df_main['windspeedKmph_6to7'] = windspeedKmph_6to7

df_main['pressureMB_7to8'] = pressureMB_7to8
df_main['pressureMB_1to2'] = pressureMB_1to2
df_main['pressureMB_6to7'] = pressureMB_6to7

df_main['precipMM_7to8'] = precipMM_7to8
df_main['precipMM_1to2'] = precipMM_1to2
df_main['precipMM_6to7'] = precipMM_6to7

df_main['weatherDesc_7to8'] = weatherDesc_7to8
df_main['weatherDesc_1to2'] = weatherDesc_1to2
df_main['weatherDesc_6to7'] = weatherDesc_6to7



df_main.head()

In [ ]:
df_main.to_csv('part4//2018-2021.csv', index=False)

In [2]:
df = pd.read_csv(r'part4/2018-2021.csv')
df.head()

,observation,tempC_7to8,tempC_1to2,tempC_6to7,humidity_7to8,humidity_1to2,humidity_6to7,windspeedKmph_7to8,windspeedKmph_1to2,windspeedKmph_6to7,pressureMB_7to8,pressureMB_1to2,pressureMB_6to7,precipMM_7to8,precipMM_1to2,precipMM_6to7,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7
0,2018-01-01,22,26,20,38,28,44,5,11,9,1012,1009,1010,0.0,0.0,0.0,Sunny,Sunny,Clear
1,2018-01-02,21,28,21,39,25,38,10,4,6,1012,1010,1011,0.0,0.0,0.0,Sunny,Sunny,Clear
2,2018-01-03,20,28,22,41,27,45,12,5,4,1014,1011,1013,0.0,0.0,0.0,Sunny,Sunny,Clear
3,2018-01-04,22,28,21,39,26,49,6,4,8,1015,1012,1013,0.0,0.0,0.0,Sunny,Sunny,Clear
4,2018-01-05,22,27,20,43,27,44,4,7,10,1014,1011,1012,0.0,0.0,0.0,Sunny,Sunny,Clear

In [3]:
# take avg. of all

# ['observation', 'tempC_7to8', 'tempC_1to2', 'tempC_6to7',
#        'humidity_7to8', 'humidity_1to2', 'humidity_6to7', 'windspeedKmph_7to8',
#        'windspeedKmph_1to2', 'windspeedKmph_6to7', 'pressureMB_7to8',
#        'pressureMB_1to2', 'pressureMB_6to7', 'precipMM_7to8', 'precipMM_1to2',
#        'precipMM_6to7', 'weatherDesc_7to8', 'weatherDesc_1to2',
#        'weatherDesc_6to7']

In [3]:
from statistics import mean

tempC_avg, humidity_avg, windspeedKmph_avg, pressureMB_avg, precipMM_avg = [],[],[],[],[]

for ind in range(len(df)):
    tempC_avg.append(mean([df['tempC_7to8'][ind],df['tempC_1to2'][ind],df['tempC_6to7'][ind]]))     
    humidity_avg.append(mean([df['humidity_7to8'][ind],df['humidity_1to2'][ind],df['humidity_6to7'][ind]]))
    windspeedKmph_avg.append(mean([df['windspeedKmph_7to8'][ind],df['windspeedKmph_1to2'][ind],df['windspeedKmph_6to7'][ind]]))
    pressureMB_avg.append(mean([df['pressureMB_7to8'][ind],df['pressureMB_1to2'][ind],df['pressureMB_6to7'][ind]]))
    precipMM_avg.append(mean([df['precipMM_7to8'][ind],df['precipMM_1to2'][ind],df['precipMM_6to7'][ind]]))

df['tempC_avg'] = tempC_avg 
df['humidity_avg'] = humidity_avg
df['windspeedKmph_avg'] = windspeedKmph_avg
df['pressureMB_avg'] = pressureMB_avg
df['precipMM_avg'] = precipMM_avg

column_names = ['observation', 'tempC_7to8', 'tempC_1to2', 'tempC_6to7', 'tempC_avg',
                'humidity_7to8', 'humidity_1to2', 'humidity_6to7', 'humidity_avg',
                'windspeedKmph_7to8', 'windspeedKmph_1to2', 'windspeedKmph_6to7', 'windspeedKmph_avg',
                'pressureMB_7to8', 'pressureMB_1to2', 'pressureMB_6to7', 'pressureMB_avg',
                'precipMM_7to8', 'precipMM_1to2', 'precipMM_6to7', 'precipMM_avg',
                'weatherDesc_7to8', 'weatherDesc_1to2','weatherDesc_6to7']

df = df.reindex(columns=column_names)

df.head()

,observation,tempC_7to8,tempC_1to2,tempC_6to7,tempC_avg,humidity_7to8,humidity_1to2,humidity_6to7,humidity_avg,windspeedKmph_7to8,...,pressureMB_1to2,pressureMB_6to7,pressureMB_avg,precipMM_7to8,precipMM_1to2,precipMM_6to7,precipMM_avg,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7
0,2018-01-01,22,26,20,22,38,28,44,36,5,...,1009,1010,1010,0.0,0.0,0.0,0.0,Sunny,Sunny,Clear
1,2018-01-02,21,28,21,23,39,25,38,34,10,...,1010,1011,1011,0.0,0.0,0.0,0.0,Sunny,Sunny,Clear
2,2018-01-03,20,28,22,23,41,27,45,37,12,...,1011,1013,1012,0.0,0.0,0.0,0.0,Sunny,Sunny,Clear
3,2018-01-04,22,28,21,23,39,26,49,38,6,...,1012,1013,1013,0.0,0.0,0.0,0.0,Sunny,Sunny,Clear
4,2018-01-05,22,27,20,23,43,27,44,38,4,...,1011,1012,1012,0.0,0.0,0.0,0.0,Sunny,Sunny,Clear

In [10]:
# # by using Python - List Comprehension

# df1 = pd.read_csv(r'part4/2018-2021.csv')

# df1['tempC_avg'] = [mean([df['tempC_7to8'][ind],df['tempC_1to2'][ind],df['tempC_6to7'][ind]]) for ind in range(len(df1))]
# df1['humidity_avg'] = [mean([df['humidity_7to8'][ind],df['humidity_1to2'][ind],df['humidity_6to7'][ind]]) for ind in range(len(df1))]
# df1['windspeedKmph_avg'] = [mean([df['windspeedKmph_7to8'][ind],df['windspeedKmph_1to2'][ind],df['windspeedKmph_6to7'][ind]]) for ind in range(len(df1))]
# df1['pressureMB_avg'] = [mean([df['pressureMB_7to8'][ind],df['pressureMB_1to2'][ind],df['pressureMB_6to7'][ind]]) for ind in range(len(df1))]
# df1['precipMM_avg'] = [mean([df['precipMM_7to8'][ind],df['precipMM_1to2'][ind],df['precipMM_6to7'][ind]]) for ind in range(len(df1))]

# column_names = ['observation', 'tempC_7to8', 'tempC_1to2', 'tempC_6to7', 'tempC_avg',
#                 'humidity_7to8', 'humidity_1to2', 'humidity_6to7', 'humidity_avg',
#                 'windspeedKmph_7to8', 'windspeedKmph_1to2', 'windspeedKmph_6to7', 'windspeedKmph_avg',
#                 'pressureMB_7to8', 'pressureMB_1to2', 'pressureMB_6to7', 'pressureMB_avg',
#                 'precipMM_7to8', 'precipMM_1to2', 'precipMM_6to7', 'precipMM_avg',
#                 'weatherDesc_7to8', 'weatherDesc_1to2','weatherDesc_6to7']

# df1 = df1.reindex(columns=column_names)

# df1.head()

In [8]:
df.tail()

,observation,tempC_7to8,tempC_1to2,tempC_6to7,tempC_avg,humidity_7to8,humidity_1to2,humidity_6to7,humidity_avg,windspeedKmph_7to8,...,pressureMB_1to2,pressureMB_6to7,pressureMB_avg,precipMM_7to8,precipMM_1to2,precipMM_6to7,precipMM_avg,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7
1185,2021-05-05,26,34,34,31,50,25,28,34,10,...,1008,1006,1008,0.0,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy
1186,2021-05-06,26,34,33,31,51,26,33,36,11,...,1009,1007,1008,0.0,0.0,0.2,0.066667,Partly cloudy,Partly cloudy,Patchy rain possible
1187,2021-05-07,26,35,34,31,59,25,32,38,14,...,1009,1008,1009,0.0,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy
1188,2021-05-08,27,34,34,31,53,27,31,37,12,...,1008,1006,1008,0.0,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy
1189,2021-05-09,28,35,33,32,48,26,32,35,13,...,1007,1006,1007,0.0,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy

In [16]:
# adding artificial values / data augmentation

soil_moisure, soil_pH, water_pH, water_TDS_mgpl  = [],[],[],[]

for ind in range(len(df)):
    if int(df['observation'][ind].split('-')[1]) == 1 or int(df['observation'][ind].split('-')[1]) == 2 or \
    int(df['observation'][ind].split('-')[1]) == 11 or int(df['observation'][ind].split('-')[1]) == 12:
        soil_moisure.append(random.randint(40,45))
    
    elif int(df['observation'][ind].split('-')[1]) == 3 or int(df['observation'][ind].split('-')[1]) == 4 or \
    int(df['observation'][ind].split('-')[1]) == 5 or int(df['observation'][ind].split('-')[1]) == 6:
        soil_moisure.append(random.randint(30,35))
        
    elif int(df['observation'][ind].split('-')[1]) == 7 or int(df['observation'][ind].split('-')[1]) == 8:
        soil_moisure.append(random.randint(45,50))
        
    elif int(df['observation'][ind].split('-')[1]) == 9 or int(df['observation'][ind].split('-')[1]) == 10:
        soil_moisure.append(random.randint(50,55))
    
    else: pass
    
    soil_pH.append(round(random.uniform(6.5, 7.5),2)) 
    water_pH.append(round(random.uniform(6.5, 8.5),2))
    
    if int(df['observation'][ind].split('-')[2])%15 == 0:
        val = random.randint(1710,1720)
        water_TDS_mgpl.append(val-(val*0.05))
    else:
        val = random.randint(1707,1710)
        water_TDS_mgpl.append(val)
        
df['%_soil_moisure'] = soil_moisure
df['soil_pH'] = soil_pH
df['water_pH'] = water_pH
df['water_TDS_mgpl'] = water_TDS_mgpl
df.head()

,observation,tempC_7to8,tempC_1to2,tempC_6to7,tempC_avg,humidity_7to8,humidity_1to2,humidity_6to7,humidity_avg,windspeedKmph_7to8,...,precipMM_1to2,precipMM_6to7,precipMM_avg,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7,%_soil_moisure,soil_pH,water_pH,water_TDS_mgpl
0,2018-01-01,22,26,20,22,38,28,44,36,5,...,0.0,0.0,0.0,Sunny,Sunny,Clear,44,6.54,6.69,1709.0
1,2018-01-02,21,28,21,23,39,25,38,34,10,...,0.0,0.0,0.0,Sunny,Sunny,Clear,43,7.23,7.43,1708.0
2,2018-01-03,20,28,22,23,41,27,45,37,12,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,7.05,7.67,1707.0
3,2018-01-04,22,28,21,23,39,26,49,38,6,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,6.52,8.44,1709.0
4,2018-01-05,22,27,20,23,43,27,44,38,4,...,0.0,0.0,0.0,Sunny,Sunny,Clear,43,7.20,7.26,1708.0

In [17]:
df.tail()

,observation,tempC_7to8,tempC_1to2,tempC_6to7,tempC_avg,humidity_7to8,humidity_1to2,humidity_6to7,humidity_avg,windspeedKmph_7to8,...,precipMM_1to2,precipMM_6to7,precipMM_avg,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7,%_soil_moisure,soil_pH,water_pH,water_TDS_mgpl
1185,2021-05-05,26,34,34,31,50,25,28,34,10,...,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy,35,7.05,6.76,1708.0
1186,2021-05-06,26,34,33,31,51,26,33,36,11,...,0.0,0.2,0.066667,Partly cloudy,Partly cloudy,Patchy rain possible,30,6.96,8.13,1708.0
1187,2021-05-07,26,35,34,31,59,25,32,38,14,...,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy,34,6.98,6.73,1707.0
1188,2021-05-08,27,34,34,31,53,27,31,37,12,...,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy,31,6.76,6.66,1710.0
1189,2021-05-09,28,35,33,32,48,26,32,35,13,...,0.0,0.0,0.000000,Partly cloudy,Partly cloudy,Partly cloudy,31,6.60,8.06,1710.0

In [18]:
df.head(20)

,observation,tempC_7to8,tempC_1to2,tempC_6to7,tempC_avg,humidity_7to8,humidity_1to2,humidity_6to7,humidity_avg,windspeedKmph_7to8,...,precipMM_1to2,precipMM_6to7,precipMM_avg,weatherDesc_7to8,weatherDesc_1to2,weatherDesc_6to7,%_soil_moisure,soil_pH,water_pH,water_TDS_mgpl
0,2018-01-01,22,26,20,22,38,28,44,36,5,...,0.0,0.0,0.0,Sunny,Sunny,Clear,44,6.54,6.69,1709.0
1,2018-01-02,21,28,21,23,39,25,38,34,10,...,0.0,0.0,0.0,Sunny,Sunny,Clear,43,7.23,7.43,1708.0
2,2018-01-03,20,28,22,23,41,27,45,37,12,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,7.05,7.67,1707.0
3,2018-01-04,22,28,21,23,39,26,49,38,6,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,6.52,8.44,1709.0
4,2018-01-05,22,27,20,23,43,27,44,38,4,...,0.0,0.0,0.0,Sunny,Sunny,Clear,43,7.20,7.26,1708.0
5,2018-01-06,22,26,19,22,40,29,43,37,4,...,0.0,0.0,0.0,Sunny,Sunny,Clear,41,6.73,7.13,1708.0
6,2018-01-07,21,25,19,21,40,26,35,33,4,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,6.64,8.07,1709.0
7,2018-01-08,20,27,21,22,34,28,38,33,10,...,0.0,0.0,0.0,Sunny,Sunny,Clear,45,7.28,8.15,1709.0
8,2018-01-09,20,27,21,22,39,28,36,34,11,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,6.52,6.78,1710.0
9,2018-01-10,21,27,22,23,42,30,41,37,15,...,0.0,0.0,0.0,Sunny,Sunny,Clear,44,6.74,8.29,1710.0
10,2018-01-11,22,30,24,25,43,34,48,41,9,...,0.0,0.0,0.0,Sunny,Sunny,Clear,41,6.91,8.10,1707.0
11,2018-01-12,24,30,25,26,36,32,42,36,12,...,0.0,0.0,0.0,Sunny,Sunny,Clear,43,6.92,7.58,1709.0
12,2018-01-13,24,30,25,26,37,30,41,36,14,...,0.0,0.0,0.0,Sunny,Sunny,Clear,44,7.19,8.05,1707.0
13,2018-01-14,25,30,25,26,40,34,52,42,7,...,0.0,0.0,0.0,Partly cloudy,Partly cloudy,Clear,41,6.73,7.99,1710.0
14,2018-01-15,26,30,25,27,38,32,44,38,6,...,0.0,0.0,0.0,Sunny,Partly cloudy,Clear,42,6.81,6.59,1630.2
15,2018-01-16,24,30,24,26,43,27,39,36,8,...,0.0,0.0,0.0,Sunny,Sunny,Clear,45,6.83,6.80,1707.0
16,2018-01-17,24,29,23,25,41,25,39,35,7,...,0.0,0.0,0.0,Sunny,Sunny,Clear,41,7.15,8.40,1707.0
17,2018-01-18,23,30,24,25,37,25,38,33,8,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,7.40,8.34,1709.0
18,2018-01-19,23,29,24,25,38,28,39,35,10,...,0.0,0.0,0.0,Sunny,Sunny,Clear,42,6.84,6.51,1709.0
19,2018-01-20,22,30,24,25,36,23,34,31,10,...,0.0,0.0,0.0,Sunny,Sunny,Clear,41,6.84,6.98,1710.0

In [19]:
df.to_csv('part5//2018-2021.csv', index=False)